//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeAhead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int Id { get; set; }
        public string Original { get; set; }
        public string Current { get; set; }
    }
}
